<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-K4RM8J37" failures="2" tests="2" name="Test" time="0.312" errors="0" timestamp="17 Feb 2022 12:51:02 GMT">
  <testcase classname="test.logintest" name="failTest" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [llavaByKiran | Log in] but found [JavaByKiran | Log in]">
      <![CDATA[java.lang.AssertionError: expected [llavaByKiran | Log in] but found [JavaByKiran | Log in]
at test.logintest.failTest(logintest.java:74)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase classname="test.logintest" name="failTest" time="0.197">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.base/java.io.File.<init>(File.java:278)
at base.Base.takesScreenshot(Base.java:66)
at listner.Listner.onTestFailure(Listner.java:32)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
</testsuite> <!-- Test -->
